version: "3"
services:

    ### 路径配置说明
    ### 在根目录创建/data1目录。如： mkdir /data1
    ### 关联git仓库到/data1/htdocs目录。如： ln -s /mnt/hgfs/kugou_git /data1/htdocs

    ### 启动docker
    ### docker-compose -f /data1/htdocs/docker_protected/local_vm/develop/docker-compose.yml up -d

    ### 查看容器内部IP
    ### docker inspect -f='{{.NetworkSettings.Networks.develop_default.IPAddress}} {{.Name}}' $(docker ps -a -q )
    ### docker inspect container_id | grep IPAddress

    ### host配置
    ### 192.168.19.129 local-newsong.kugou.com
    ### 192.168.19.129 local-mobileservice.kugou.com
    ### 192.168.19.129 local-service.mobile.kugou.com
    ### 192.168.19.129 local-config.mobile.kugou.com
    ### 192.168.19.129 local-update.mobile.kugou.com

    ### todo
    ### redis、mysql 等可再独立配置到docker，现公用 测试环境
    ### 本地测试配置，与线上配置问题，尽量一个项目配置存在一个文件差异就能达到切换效果
    ### rpc 调用问题，尝试使用iptables添加规则解决，php的docker容器无法使用nginx代理中转，目前只能屏蔽rpc使用

    ### 调试技巧
    ### whistle 工具抓包
    ### 查看：iptables -L -t nat
    ### 设置：iptables -t nat -A PREROUTING -s 172.19.1.1/16 ! -d 172.19.1.1/16 -p tcp -m multiport --dports 80,19980 -j DNAT --to 192.168.163.141:8899
    ### 删除：iptables -t nat -D PREROUTING x

    ### redis/mysql IP端口转发
    ### 设置：iptables -t nat -A PREROUTING -s 172.19.1.1/16 -p tcp -m multiport --dports 6379 -j DNAT --to 192.168.163.134:8899
    ### 删除：iptables -t nat -D PREROUTING x


    # 模拟公共接入层
    docker_proxy:
        image: 10.16.4.154:8080/library/openresty/openresty:1.11.2.2-centos-rpm
        ports:
            - "80:80"
        links:
            - "work"
        volumes:
            - ./docker_proxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
            - ./docker_proxy/vhost:/usr/local/openresty/nginx/conf/vhost/:ro
            - /data1/logs:/data1/logs/
        restart: always

    # 通用PHP5.6模块，如果有不一样的版本配置，可单独配置镜像
    php56:
        image: 10.16.4.154:8080/library/kg_php:5.6.39-fpm
        volumes:
            - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
            - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - /data1/htdocs:/data1/htdocs/
            - /data1/logs:/data1/logs/
        restart: always
        cap_add:
            - SYS_PTRACE

    # 通用PHP72模块，如果有不一样的版本配置，可单独配置镜像
    php72:
        image: 10.16.4.154:8080/library/kg_php:7.2.13-fpm
        volumes:
            - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
            - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./php/hosts:/etc/hosts:ro
            - /data1/logs:/data1/logs/
            - /data1/htdocs/admin_publicAccess_protected/:/data1/htdocs/admin_publicAccess_protected/
            - /data1/htdocs/work.kugou.net/:/data1/htdocs/work.kugou.net/
            - /data1/htdocs/test/:/data1/htdocs/test/
        restart: always
        cap_add:
            - SYS_PTRACE

    # 虚拟团后台
    work:
        image: 10.16.4.154:8080/library/openresty/openresty:1.11.2.2-centos-rpm
        links:
            - "php72"
        container_name: work
        volumes:
            - ./work.kugou.net/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./work.kugou.net/nginx/vhost/:/usr/local/openresty/nginx/conf/vhost/
            - /data1/htdocs/work.kugou.net/:/data1/htdocs/work.kugou.net/
            - /data1/logs:/data1/logs
        restart: always
        cap_add:
            - SYS_PTRACE

    mysql_db:
        ports:
            - "3308:3306"
        image: mysql:5.7
        container_name: mysql_db
        restart: always
        volumes:
            - /data1/docker_data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root







